# Form implementation generated from reading ui file 'layout.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(803, 520)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.lista = QtWidgets.QComboBox(parent=Dialog)
        self.lista.setGeometry(QtCore.QRect(470, 130, 281, 31))
        self.lista.setObjectName("lista")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(10, 60, 411, 61))
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.widget = QtWidgets.QWidget(parent=Dialog)
        self.widget.setGeometry(QtCore.QRect(12, 135, 411, 331))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_name = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.gridLayout.addWidget(self.lineEdit_name, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.lineEdit_surname = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_surname.setObjectName("lineEdit_surname")
        self.gridLayout.addWidget(self.lineEdit_surname, 1, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.lineEdit_phone = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_phone.setObjectName("lineEdit_phone")
        self.gridLayout.addWidget(self.lineEdit_phone, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.lineEdit_pesel = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_pesel.setObjectName("lineEdit_pesel")
        self.gridLayout.addWidget(self.lineEdit_pesel, 3, 1, 1, 1)
        self.checkbox_work = QtWidgets.QCheckBox(parent=self.widget)
        self.checkbox_work.setObjectName("checkbox_work")
        self.gridLayout.addWidget(self.checkbox_work, 4, 0, 1, 2)
        self.save = QtWidgets.QPushButton(parent=self.widget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 5, 0, 1, 1)
        self.saveFile = QtWidgets.QPushButton(parent=self.widget)
        self.saveFile.setObjectName("saveFile")
        self.gridLayout.addWidget(self.saveFile, 5, 1, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "podaj swoje dane pls 👉👈"))
        self.label_2.setText(_translate("Dialog", "imię:"))
        self.label_3.setText(_translate("Dialog", "nazwisko:"))
        self.label_4.setText(_translate("Dialog", "nr. telefonu:"))
        self.label_5.setText(_translate("Dialog", "PESEL:"))
        self.checkbox_work.setText(_translate("Dialog", "umowa o prace"))
        self.save.setText(_translate("Dialog", "zapisz"))
        self.saveFile.setText(_translate("Dialog", "zapisz do pliku"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
